### ISSUE TITLE
CSV repeat first line causes header repetition when run for the 2nd time

### ISSUE THREAD

**Issue by prathamesh-gharat** [alexandrainst/node-red-contrib-chunks-to-lines#2]
I have a 1 minute CRON timer -> CSV API -> chunk-to-lines -> debug in a flow.

Inject[tick=true] -> chunk-to-lines (for manually checking).

From the 2nd time onwards the header rows starts repeating from the chunk-to-lines node.

**Comment by Alkarex** [comment]
Hello,
I am not sure I have understood the problem, and maybe it is just as it should be: "CSV (repeat first line)" mode is precisely made to repeat the headers (so that downstream nodes can know which column is which).
If you do not want that, try the "Text" or "JSON Array" modes.

If you still believe there is a problem, please provide some examples of input and output messages (the whole message and not only the payload).
